### ISSUE TITLE
Grammatik Fehler auf der Homepage! | Timeline Überarbeitung

### ISSUE THREAD

**Issue by Lephalu** [Cubyx-Network/website#140]
Sehr geehrtes Cubyx Team,

ich möchte Ihre Aufmerksamkeit auf einen Grammatikfehler auf Ihrer Homepage lenken, der sich auf der ersten Seite im Zeitstrahl befindet. Im Abschnitt "Juni 2022" fehlt im Text nach dem Wort "wird" ein "ein", um der deutschen Grammatik zu entsprechen.

Mit freundlichen Grüßen,
Lephu

**Comment by SachsenspieltCoding** [comment]
@LinkLuigiMaster Meinung? Ich sehe da jetzt keinen groben Fehler drin.
Es geht ja um "Cubyx wird Netzwerk Team", oder?
